### ISSUE TITLE
How can I add additional interactive elements to the GridItems?

### ISSUE THREAD

**Issue by thormuller** [cuire/svelte-grid-extended#47]
I'd like to add, for instance, Like and Remove buttons attached to each GridItem. What is the recommended approach to incorporating these additional behaviors in an implementation?

**Comment by cuire** [comment]
Hey, its a bit tricky because of event propagation. You can use something like [this](https://svelte.dev/repl/6af014e1f754458dbc15c1823dbdca3c?version=4.1.2) to prevent it or consider implementing a custom drag handle like [this](https://svelte.dev/repl/5f9dbbd845cc40f6a222734856fc9b1d?version=4.1.1).

**Comment by thormuller** [comment]
Very helpful, thanks! Appreciate your work on this library.
